[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "html-table-parse>=0.2.2",
    "langchain-text-splitters>=1.1.2",
    "mineru[core]>=3.4.5",
    "ollama>=0.6.2",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
rag = "rag:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "test",
]
